HomeLoanCost/Models/Line.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HomeLoanCost.Models
{
    public class Line
    {
        public int Month { get; set; }

        public decimal Interest { get; set; }

        public decimal Credit { get; set; }
    }
}

HomeLoanCost/Models/Loan.cs
using HomeLoanCost.Infrastructure;
using System;
using System.Collections.Generic;

namespace HomeLoanCost.Models
{
    public class Loan
    {
        public Loan()
        {
            Payments = new List<Payment>();
        }

        public double Credit { get; set; }

        public double InterestRate { get; set; }

        public double Years { get; set; }

        public const double PaymentsCountPerYear = 12;

        public double PaymentsCount => Years * PaymentsCountPerYear;

        public List<Payment> Payments { get; set; }



        /// <summary>
        /// Calculation algorithm described in http://lt.wikipedia.org/wiki/Anuitetas.
        /// </summary>
        public double GetAnnuityPaymentSum()
        {
            double monthlyInterestRateValue = GetPercentValue(InterestRate / PaymentsCountPerYear);

            double multiplier = Math.Pow(1D + monthlyInterestRateValue, 1D / PaymentsCountPerYear) - 1D;

            double divisor = Math.Pow(1D + monthlyInterestRateValue, Years);

            double annuityRate = (multiplier * divisor) / (divisor - 1D);

            double annuitySum = RoudingHelper.Round(annuityRate * Credit);

            return annuitySum;
        }

        public double GetLinearPaymentSum()
        {
            return 0;
        }

        public double GetPercentValue(double percent)
        {
            return RoudingHelper.Round(percent / 100D, 5);
        }
    }
}

HomeLoanCost/Models/Payment.cs
namespace HomeLoanCost.Models
{
    public class Payment
    {
        public int Month { get; set; }

        public double Sum { get; set; }

        public double Interest { get; set; }

        public double Repayment { get; set; }

        public double Credit { get; set; }
    }
}

HomeLoanCost/Models/PaymentType.cs
namespace HomeLoanCost.Models
{
    public class PaymentType
    {
        public int Id { get; set; }

        public string Name { get; set; }
    }
}

HomeLoanCost/Controllers/LoansController.cs
using System.Linq;
using HomeLoanCost.Infrastructure;
using HomeLoanCost.Models;
using System.Web.Mvc;

namespace HomeLoanCost.Controllers
{
    public class LoansController : Controller
    {
        public ActionResult Landing()
        {
            return View();
        }

        public ActionResult Calculate(Loan loan)
        {
            double credit = loan.Credit;

            double sum = loan.GetAnnuityPaymentSum();
            
            for (int month = 1; month <= loan.PaymentsCount; month++)
            {
                var line = new Payment();
                
                line.Month = month;
                line.Sum = sum;
                line.Interest = RoudingHelper.Round(((loan.InterestRate / 12) / 100) * credit);
                line.Repayment = RoudingHelper.Round(line.Sum - line.Interest);
                double repayment = loan.Payments.Count == 0 ? line.Repayment : loan.Payments.Last().Repayment;
                credit = RoudingHelper.Round(credit - repayment);
                line.Credit = month == 1 ? loan.Credit : RoudingHelper.Round(loan.Payments.Last().Credit - loan.Payments.Last().Repayment);
                loan.Payments.Add(line);
            }

            return View("Landing", loan);
        }
    }
}

HomeLoanCost/Views/Loans/Landing.cshtml
@model HomeLoanCost.Models.Loan

@{
    ViewBag.Title = "Būsto kredito skaičiuoklė - sužinokite kaip sutaupysite daugiausia";
}

<h2>Būsto kredito skaičiuoklė</h2>

<form id="formId" action="@Url.Action("Calculate", "Loans")" method="POST">

    Paskolos grąžinimo būdas
    @*@Html.DropDownListFor(l => l.)*@
    <br /><br />

    Paskolos suma 
    @Html.TextBoxFor(m => m.Credit)
    
    <br/><br/>
    
    Paskolos palūkanos
    @Html.TextBoxFor(m => m.InterestRate)
    
    <br/><br/>
    
    Paskola laikotarpiui (metai)
    @Html.TextBoxFor(m => m.Years)
    
    <br /><br />

    <input id="btnCalculate" class="btn btn-success btn-sm" type="submit" value="Skaičiuoti!" />
</form>

<table class="table table-striped">


    @if (Model != null && Model.Payments != null && Model.Payments.Count > 0)
    {
        foreach (var payment in Model.Payments)
        {
            <tr>@payment.Month   @payment.Sum     @payment.Interest                  @payment.Repayment                    @payment.Credit</tr>
            <br />
        }
    }
</table>

HomeLoanCost/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Būsto paskolos skaičiuoklė</title>
    <link href="//netdna.bootstrapcdn.com/bootswatch/3.0.3/readable/bootstrap.min.css" rel="stylesheet">
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet">
    <script src="//code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
</head>
<body>
    @RenderBody()
</body>
</html>